# FROM --platform=${TARGETPLATFORM} xkas/alpine-nginx-full:latest
FROM xkas/alpine-nginx-full:1.0.0
LABEL maintainer="xkas"

RUN apk update \
	&& apk add --update python2 gcc g++ musl-dev make build-base git npm nodejs-current yarn \
	&& rm -rf /var/cache/apk/*
